# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dockerfile:
              - 'Dockerfile'
            dockerfile-ocp:
              - 'Dockerfile-ocp'
        
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          username: erezo
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.HUB_PASSWORD }}
      
      - name: Download and extract OpenShift client
        if: steps.changes.outputs.dockerfile-ocp == 'true'
        run: |
          wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.10.67/openshift-client-linux.tar.gz
          tar -xzf openshift-client-linux.tar.gz
          # Assuming Dockerfile-ocp expects 'oc' in the root context; adjust if needed
      
      - name: Build and push Docker images
        if: steps.changes.outputs.dockerfile == 'true'
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@4a531fa5a603bab87dfa56578bd82b28508c9547
        uses: docker/build-push-action@v2.2.2
        with:
          context:  .
          file:  ./Dockerfile
          tags:  erezo/terraform-mongo:1.9
          push:  true
      
      - name: Build and push Docker images
        if: steps.changes.outputs.dockerfile-ocp == 'true'
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@4a531fa5a603bab87dfa56578bd82b28508c9547
        uses: docker/build-push-action@v2.2.2
        with:
          context:  .
          file:  ./Dockerfile-ocp
          tags:  erezo/ansible-runner:4.4.0
          push:  true

